import { Entity, Column, PrimaryGeneratedColumn, CreateDateColumn } from 'typeorm';

@Entity()
export class Attack {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  timeStr: string;

  @Column()
  ip: string;

  @Column()
  type: string;

  @Column()
  severity: string;

  @Column()
  detail: string;

  @Column({ nullable: true })
  mitigation: string;

  @Column({ nullable: true })
  country: string;

  @Column({ nullable: true })
  clientVersion: string;

  @Column({ nullable: true })
  mitreCode: string;

  @Column({ type: 'int', default: 50 })
  threatScore: number;

  @Column({ default: 'Opened' })
  status: string;

  @Column({ nullable: true })
  sessionId: string;

  @Column({ type: 'bigint', nullable: true })
  timestampMs: number;

  // AI analysis result (Thai language, generated by Gemini or rule-based engine)
  @Column({ type: 'text', nullable: true })
  aiAnalysis: string;

  @CreateDateColumn()
  createdAt: Date;
}

