import { get } from 'svelte/store';
import { usernameStore } from '../../stores/events';

export async function downloadAiReportPDF(data: any, selectedEvents: any[], filename = 'ai_security_report.pdf', language = 'en') {
  try {
    const { jsPDF } = (window as any).jspdf;
    const doc = new jsPDF('portrait', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.width || doc.internal.pageSize.getWidth();
    
    const exporter = get(usernameStore) || 'System Administrator';
    const dateStr = new Date().toLocaleString(language === 'th' ? 'th-TH' : 'en-GB');
    
    // Header
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, pageWidth, 24, 'F');
    doc.setFontSize(16);
    doc.setTextColor(255, 255, 255);
    const inst = language === 'th' ? 'สำนักงานเทคโนโลยีดิจิทัล มหาวิทยาลัยขอนแก่น' : 'Digital Technology Office, KKU';
    doc.text(`KKUSIEM AI Daily Security Report`, 14, 15);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.text(`1. Executive Security Summary`, 14, 40);
    
    doc.setFontSize(10);
    const summaryLines = doc.splitTextToSize(data.executiveSummary || 'No summary available.', pageWidth - 28);
    doc.text(summaryLines, 14, 50);
    
    doc.setFontSize(14);
    doc.text(`2. Security Statistics`, 14, 100);
    doc.setFontSize(10);
    doc.text(`Total Events: ${selectedEvents.length}`, 14, 110);
    
    // Mock the rest of the PDF generation...
    // In reality this would draw all 11 sections.
    doc.text(`Generated by: ${exporter} at ${dateStr}`, 14, 280);
    doc.text(`Issued by: ${inst}`, 14, 285);
    
    doc.save(filename);
  } catch (e) {
    console.error("PDF Generation failed", e);
  }
}
